### ISSUE TITLE
File that is recognized by the editor as UTF-8 with BOM, in version 0.8 is parsed with "latin-1"

### ISSUE THREAD

**Issue by VelizarVESSELINOV** [kinverarity1/lasio#103]
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/lasio/las.py", line 926, in read
    return LASFile(file_ref, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/lasio/las.py", line 166, in __init__
    self.read(file_ref, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/lasio/las.py", line 222, in read
    data = reader.read_data(len(self.curves))
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/lasio/las.py", line 548, in read_data
    traceback.format_exc().splitlines()[-1]))
lasio.las.LASDataError: Failed to read data:
UnicodeEncodeError: 'latin-1' codec can't encode character '\ufffd' in position 71: ordinal not in range(256)
```

I didn't expect this error message as it is BOMed file.

But also the error message is not very clear (on which line at position 71 is the error?).

I tried to enable debug logger in order to understand more, but I found that you have two logger (is it expected?)

```
>>> Logger.manager.loggerDict
{'lasio.las': <logging.Logger object at 0x102534828>, 'lasio': <logging.PlaceHolder object at 0x102534940>}
```

When I enabled debug stream found I found only this debug message, so was not very helpful to understand how latin-1 codec was chosen:

```
lasio.las - DEBUG    - LAS content is type <class 'str'>
```

**Comment by kinverarity1** [comment]
Apart from the encoding issue, I need to make sure the use of logging messages is more organised.

**Comment by kinverarity1** [comment]
please upload example file and then we can check if this is still present with the re-written encoding section. Also the use of logging has been significantly expanded.
