### ISSUE TITLE
ValueError: Wrong number of columns at line 15

### ISSUE THREAD

**Issue by kinverarity1** [kinverarity1/lasio#16]
```
D:\study\2015\las_kgs_test\2001_2005\1031902741.las Traceback (most recent call last):
  File ".\basic_read_test.py", line 19, in <module>
    l = las_reader.read(fn)
  File "d:\work\dewnr\logging_software\las_reader\las_reader\__init__.py", line 5, in read
    return las.LASFile(file)
  File "d:\work\dewnr\logging_software\las_reader\las_reader\las.py", line 121, in __init__
    self.read(file, **kwargs)
  File "d:\work\dewnr\logging_software\las_reader\las_reader\las.py", line 143, in read
    data = reader.read_data(len(self.curves))
  File "d:\work\dewnr\logging_software\las_reader\las_reader\las.py", line 416, in read_data
    arr = numpy.loadtxt(StringIO(s))
  File "C:\Users\kent\Anaconda\lib\site-packages\numpy\lib\npyio.py", line 853, in loadtxt
    % line_num)
ValueError: Wrong number of columns at line 15
```

**Comment by kinverarity1** [comment]
Not enough info to be a useful report.

**Comment by kinverarity1** [comment]
At some point this was fixed. With ``master`` now:

```ipython
In [4]: las = lasio.read('../las/examples/kgs_downloads/2001_2005/1031902741.las')

In [5]: las.curves
Out[5]:
[CurveItem(mnemonic=DEPT, unit=FT, value=, descr=Depth in Feet, original_mnemonic=DEPT, data.shape=(241,)),
 CurveItem(mnemonic=GR, unit=GAPI, value=, descr=Gamma Ray, original_mnemonic=GR, data.shape=(241,)),
 CurveItem(mnemonic=LLS, unit=OHMM, value=, descr=Latero-Log Shallow (Resistivity), original_mnemonic=LLS, data.shape=(241,)),
 CurveItem(mnemonic=ILM, unit=OHMM, value=, descr=Medium Induction Standard Processed Resistivity, original_mnemonic=ILM, data.shape=(241,)),
 CurveItem(mnemonic=ILD, unit=OHMM, value=, descr=Deep Induction Standard Processed Resistivity, original_mnemonic=ILD, data.shape=(241,))]

In [6]: las.data
Out[6]:
array([[ 1600.   ,   222.649,     3.777,     2.846,     2.697],
       [ 1600.5  ,   224.159,     3.748,     2.851,     2.71 ],
       [ 1601.   ,   227.391,     3.724,     2.869,     2.718],
       ...,
       [ 1719.   ,       nan,       nan,       nan,       nan],
       [ 1719.5  ,       nan,       nan,       nan,       nan],
       [ 1720.   ,       nan,       nan,       nan,       nan]])
```

**Comment by kinverarity1** [comment]
Ah it was fixed by the ``null_policy='common'`` default fix.

```
  1604.000    286.225      4.066      3.004      2.838 
  1604.500    284.503      4.015      3.004      2.846 
  1605.000    277.457      3.960      2.986      2.846 
  1605.500    267.497      3.941      2.967      2.846 
  1606.000    263.868      3.914      2.967      2.846 
  1606.500    267.947      3.895      2.958      2.846 
  1607.000     -1.#IO     -1.#IO     -1.#IO     -1.#IO 
  1607.500     -1.#IO     -1.#IO     -1.#IO     -1.#IO 
  1608.000     -1.#IO     -1.#IO     -1.#IO     -1.#IO 
  1608.500     -1.#IO     -1.#IO     -1.#IO     -1.#IO 
  1609.000     -1.#IO     -1.#IO     -1.#IO     -1.#IO 
  1609.500     -1.#IO     -1.#IO     -1.#IO     -1.#IO
```
