### ISSUE TITLE
ValueError: invalid literal for float(): 0,087

### ISSUE THREAD

**Issue by kinverarity1** [kinverarity1/lasio#17]
```
D:\study\2015\las_kgs_test\2001_2005\1031712032.las Traceback (most recent call last):
  File ".\basic_read_test.py", line 19, in <module>
    l = las_reader.read(fn)
  File "d:\work\dewnr\logging_software\las_reader\las_reader\__init__.py", line 5, in read
    return las.LASFile(file)
  File "d:\work\dewnr\logging_software\las_reader\las_reader\las.py", line 121, in __init__
    self.read(file, **kwargs)
  File "d:\work\dewnr\logging_software\las_reader\las_reader\las.py", line 143, in read
    data = reader.read_data(len(self.curves))
  File "d:\work\dewnr\logging_software\las_reader\las_reader\las.py", line 416, in read_data
    arr = numpy.loadtxt(StringIO(s))
  File "C:\Users\kent\Anaconda\lib\site-packages\numpy\lib\npyio.py", line 856, in loadtxt
    items = [conv(val) for (conv, val) in zip(converters, vals)]
ValueError: invalid literal for float(): 0,087
```

**Comment by kinverarity1** [comment]
So strange, only one character incorrect in thousands of lines:

```
2744.00 0.018   8.81   3.76 0.074 0.132 0.101 0.671 0.068 0.089   2.77   0.5   2.58
2745.00 0.071  11.84   3.89 0.080 0.123 0,087 0.640 0.056 0.089   2.74   0.4   2.57
2746.00 0.235  11.68  11.68 0.000 0.000 0.000 1.000 0.000 0.000   2.73   0.4   2.60
```
