### ISSUE TITLE
IndexError: index 3 is out of bounds for axis 1 with size 3

### ISSUE THREAD

**Issue by kinverarity1** [kinverarity1/lasio#18]
```

D:\study\2015\las_kgs_test\2006_2011\1042437385.las Traceback (most recent call last):
  File ".\basic_read_test.py", line 19, in <module>
    l = las_reader.read(fn)
  File "d:\work\dewnr\logging_software\las_reader\las_reader\__init__.py", line 5, in read
    return las.LASFile(file)
  File "d:\work\dewnr\logging_software\las_reader\las_reader\las.py", line 121, in __init__
    self.read(file, **kwargs)
  File "d:\work\dewnr\logging_software\las_reader\las_reader\las.py", line 161, in read
    d = data[:, i]
IndexError: index 3 is out of bounds for axis 1 with size 3
```

**Comment by kinverarity1** [comment]
fixed by #190
