### ISSUE TITLE
ValueError: could not convert string to float: ********

### ISSUE THREAD

**Issue by kinverarity1** [kinverarity1/lasio#21]
```
D:\study\2015\las_kgs_test\1999\1999\1006346380.las
Traceback (most recent call last):
  File ".\basic_read_test.py", line 20, in <module>
    l = las_reader.read(fn)
  File "d:\work\dewnr\logging_software\las_reader\las_reader\__init__.py", line 5, in read
    return las.LASFile(file)
  File "d:\work\dewnr\logging_software\las_reader\las_reader\las.py", line 132, in __init__
    self.read(file, **kwargs)
  File "d:\work\dewnr\logging_software\las_reader\las_reader\las.py", line 157, in read
    data = reader.read_data(len(self.curves))
  File "d:\work\dewnr\logging_software\las_reader\las_reader\las.py", line 436, in read_data
    traceback.format_exc()))
LASDataError: Failed to read data:
Traceback (most recent call last):
  File "d:\work\dewnr\logging_software\las_reader\las_reader\las.py", line 433, in read_data
    arr = numpy.loadtxt(StringIO(s))
  File "C:\Users\kent\Anaconda\lib\site-packages\numpy\lib\npyio.py", line 856, in loadtxt
    items = [conv(val) for (conv, val) in zip(converters, vals)]
ValueError: could not convert string to float: ********
```

**Comment by kinverarity1** [comment]
Should be handled with PR #170's ``ignore_data_errors=True``
