### ISSUE TITLE
package broken in v0.18

### ISSUE THREAD

**Issue by kinverarity1** [kinverarity1/lasio#223]
```
(test3) C:\Program Files (x86)>pip install lasio==0.17
Collecting lasio==0.17
  Using cached lasio-0.17-py2.py3-none-any.whl
Collecting ordereddict (from lasio==0.17)
Requirement already satisfied: numpy in c:\program files (x86)\misc\envs\test3\lib\site-packages (from lasio==0.17)
Installing collected packages: ordereddict, lasio
Successfully installed lasio-0.17 ordereddict-1.1

(test3) C:\Program Files (x86)>pip install --upgrade lasio
Collecting lasio
  Using cached lasio-0.18-py2.py3-none-any.whl
Requirement already up-to-date: ordereddict in c:\program files (x86)\misc\envs\test3\lib\site-packages (from lasio)
Requirement already up-to-date: numpy in c:\program files (x86)\misc\envs\test3\lib\site-packages (from lasio)
Installing collected packages: lasio
  Found existing installation: lasio 0.17
    Uninstalling lasio-0.17:
      Successfully uninstalled lasio-0.17
Successfully installed lasio-0.18

(test3) C:\Program Files (x86)>python
Python 2.7.14 |Anaconda, Inc.| (default, Nov  8 2017, 13:40:13) [MSC v.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import lasio
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files (x86)\MISC\envs\test3\lib\site-packages\lasio\__init__.py", line 15, in <module>
    with open(os.path.join(os.path.dirname(__file__), '..', 'VERSION')) as version_file:
IOError: [Errno 2] No such file or directory: 'C:\\Program Files (x86)\\MISC\\envs\\test3\\lib\\site-packages\\lasio\\..\\VERSION'
>>>
```

**Comment by kinverarity1** [comment]
Fixed in v0.19

```cmd
(test4) C:\Program Files (x86)\MISC\kent\lasio>pip install lasio==0.18
Collecting lasio==0.18
  Using cached lasio-0.18-py2.py3-none-any.whl
Collecting ordereddict (from lasio==0.18)
Requirement already satisfied: numpy in c:\program files (x86)\misc\envs\test4\lib\site-packages (from lasio==0.18)
Installing collected packages: ordereddict, lasio
Successfully installed lasio-0.18 ordereddict-1.1

(test4) C:\Program Files (x86)\MISC\kent\lasio>python
Python 2.7.14 |Anaconda, Inc.| (default, Nov  8 2017, 13:40:13) [MSC v.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import lasio
>>> lasio
<module 'lasio' from 'lasio\__init__.py'>
>>> exit()

(test4) C:\Program Files (x86)\MISC\kent\lasio>cd \

(test4) C:\>python
Python 2.7.14 |Anaconda, Inc.| (default, Nov  8 2017, 13:40:13) [MSC v.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import lasio
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files (x86)\MISC\envs\test4\lib\site-packages\lasio\__init__.py", line 15, in <module>
    with open(os.path.join(os.path.dirname(__file__), '..', 'VERSION')) as version_file:
IOError: [Errno 2] No such file or directory: 'C:\\Program Files (x86)\\MISC\\envs\\test4\\lib\\site-packages\\lasio\\..\\VERSION'
>>> exit()

(test4) C:\>pip install --upgrade lasio
Collecting lasio
  Downloading lasio-0.19-py2.py3-none-any.whl
Requirement already up-to-date: ordereddict in c:\program files (x86)\misc\envs\test4\lib\site-packages (from lasio)
Requirement already up-to-date: numpy in c:\program files (x86)\misc\envs\test4\lib\site-packages (from lasio)
Installing collected packages: lasio
  Found existing installation: lasio 0.18
    Uninstalling lasio-0.18:
      Successfully uninstalled lasio-0.18
Successfully installed lasio-0.19

(test4) C:\>python
Python 2.7.14 |Anaconda, Inc.| (default, Nov  8 2017, 13:40:13) [MSC v.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import lasio
>>> lasio.LASFile()
<lasio.las.LASFile object at 0x02791530>
```
