### ISSUE TITLE
LASHeaderError: Failed in ~W section on line: Sec.           14

### ISSUE THREAD

**Issue by kinverarity1** [kinverarity1/lasio#23]
```
D:\study\2015\las_kgs_test\2006_2011\1043562819.las
Traceback (most recent call last):
  File ".\basic_read_test.py", line 20, in <module>
    l = las_reader.read(fn)
  File "d:\work\dewnr\logging_software\las_reader\las_reader\__init__.py", line 5, in read
    return las.LASFile(file)
  File "d:\work\dewnr\logging_software\las_reader\las_reader\las.py", line 132, in __init__
    self.read(file, **kwargs)
  File "d:\work\dewnr\logging_software\las_reader\las_reader\las.py", line 149, in read
    self.well = reader.read_section('~W')
  File "d:\work\dewnr\logging_software\las_reader\las_reader\las.py", line 411, in read_section
    section_name, line, traceback.format_exc()))
LASHeaderError: Failed in ~W section on line:
Sec.           14
Traceback (most recent call last):
  File "d:\work\dewnr\logging_software\las_reader\las_reader\las.py", line 408, in read_section
    values = read_line(line)
  File "d:\work\dewnr\logging_software\las_reader\las_reader\las.py", line 529, in read_line
    for key, value in m.groupdict().items():
AttributeError: 'NoneType' object has no attribute 'groupdict'
```

**Comment by kinverarity1** [comment]
```
D:\study\2015\las_kgs_test\2014\1044831148.las
Traceback (most recent call last):
  File ".\basic_read_test.py", line 20, in <module>
    l = las_reader.read(fn)
  File "d:\work\dewnr\logging_software\las_reader\las_reader\__init__.py", line 5, in read
    return las.LASFile(file)
  File "d:\work\dewnr\logging_software\las_reader\las_reader\las.py", line 132, in __init__
    self.read(file, **kwargs)
  File "d:\work\dewnr\logging_software\las_reader\las_reader\las.py", line 151, in read
    self.params = reader.read_section('~P')
  File "d:\work\dewnr\logging_software\las_reader\las_reader\las.py", line 411, in read_section
    section_name, line, traceback.format_exc()))
LASHeaderError: Failed in ~P section on line:
R3   .        Main Pass logged from SLB TD to CSG.
Traceback (most recent call last):
  File "d:\work\dewnr\logging_software\las_reader\las_reader\las.py", line 408, in read_section
    values = read_line(line)
  File "d:\work\dewnr\logging_software\las_reader\las_reader\las.py", line 529, in read_line
    for key, value in m.groupdict().items():
AttributeError: 'NoneType' object has no attribute 'groupdict'
```

**Comment by kinverarity1** [comment]
I'm not going to fix the parser for these header errors, where header lines are missing the period or colon. Instead, use the ignore_header_errors argument.

```ipython
In [8]: las = lasio.read('../las/examples/kgs_downloads/2006_2011/1043562819.las', ignore_header_errors=True)
line 14 (section ~Well Information Block): "Sec.           14"
line 15 (section ~Well Information Block): "Twp.           30S"
line 16 (section ~Well Information Block): "Rge.           41W"
line 17 (section ~Well Information Block): "API.           15-187-21105"
line 18 (section ~Well Information Block): "GL.            3355"
line 19 (section ~Well Information Block): "KB.            3364"

In [9]:
```
