### ISSUE TITLE
Error when reading las file [containing text in ~Data section]

### ISSUE THREAD

**Issue by mrlarssen** [kinverarity1/lasio#236]
When trying to read a las file using

```
las.read('my_las_file.las')
```

I'm getting the following error:

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/opt/conda/lib/python3.6/site-packages/lasio/reader.py in read_file_contents(file_obj, regexp_subs, value_null_subs, ignore_data)
    275                 try:
--> 276                     data = read_data_section_iterative(file_obj, regexp_subs, value_null_subs)
    277                 except:

/opt/conda/lib/python3.6/site-packages/lasio/reader.py in read_data_section_iterative(file_obj, regexp_subs, value_null_subs)
    353 
--> 354     array = np.fromiter(items(file_obj), np.float64, -1)
    355     for value in value_null_subs:

ValueError: could not convert string to float: 'solidrock'

During handling of the above exception, another exception occurred:

LASDataError                              Traceback (most recent call last)
<ipython-input-136-093a43e5102b> in <module>()
     10     
     11         
---> 12             las.read('my_las_file.las')
     13 
     14 

/opt/conda/lib/python3.6/site-packages/lasio/__init__.py in read(file_ref, **kwargs)
     39 
     40     '''
---> 41     return LASFile(file_ref, **kwargs)

/opt/conda/lib/python3.6/site-packages/lasio/las.py in __init__(self, file_ref, **read_kwargs)
     76 
     77         if not (file_ref is None):
---> 78             self.read(file_ref, **read_kwargs)
     79 
     80     def read(self, file_ref, 

/opt/conda/lib/python3.6/site-packages/lasio/las.py in read(self, file_ref, ignore_data, read_policy, null_policy, ignore_header_errors, mnemonic_case, **kwargs)
    111         try:
    112             self.raw_sections = reader.read_file_contents(
--> 113                 file_obj, regexp_subs, value_null_subs, ignore_data=ignore_data, )
    114         finally:
    115             if hasattr(file_obj, "close"):

/opt/conda/lib/python3.6/site-packages/lasio/reader.py in read_file_contents(file_obj, regexp_subs, value_null_subs, ignore_data)
    278                     raise exceptions.LASDataError(
    279                         traceback.format_exc()[:-1] +
--> 280                         ' in data section beginning line {}'.format(i + 1))
    281                 sections[line] = {
    282                     "section_type": "data",

LASDataError: Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/lasio/reader.py", line 276, in read_file_contents
    data = read_data_section_iterative(file_obj, regexp_subs, value_null_subs)
  File "/opt/conda/lib/python3.6/site-packages/lasio/reader.py", line 354, in read_data_section_iterative
    array = np.fromiter(items(file_obj), np.float64, -1)
ValueError: could not convert string to float: 'solidrock' in data section beginning line 57

```

The reader seems to have trouble parsing text columns? Any ideas?
(Null values are represented as -999.25 in this column as well)

**Comment by kinverarity1** [comment]
Yes text columns are part of the LAS 3 standard which is unfortunately not supported by lasio yet.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by kinverarity1** [comment]
This may now be working based on changes from #245 - if you can send or  upload an example file I can test it for you.
