### ISSUE TITLE
LASHeaderError: Failed in ~W section on line: COUNTY: RUSSELL

### ISSUE THREAD

**Issue by kinverarity1** [kinverarity1/lasio#26]
```
D:\study\2015\las_kgs_test\2012\1044094833.las
Traceback (most recent call last):
  File ".\basic_read_test.py", line 20, in <module>
    l = las_reader.read(fn)
  File "d:\work\dewnr\logging_software\las_reader\las_reader\__init__.py", line 5, in read
    return las.LASFile(file)
  File "d:\work\dewnr\logging_software\las_reader\las_reader\las.py", line 132, in __init__
    self.read(file, **kwargs)
  File "d:\work\dewnr\logging_software\las_reader\las_reader\las.py", line 149, in read
    self.well = reader.read_section('~W')
  File "d:\work\dewnr\logging_software\las_reader\las_reader\las.py", line 411, in read_section
    section_name, line, traceback.format_exc()))
LASHeaderError: Failed in ~W section on line:
COUNTY: RUSSELL
Traceback (most recent call last):
  File "d:\work\dewnr\logging_software\las_reader\las_reader\las.py", line 408, in read_section
    values = read_line(line)
  File "d:\work\dewnr\logging_software\las_reader\las_reader\las.py", line 529, in read_line
    for key, value in m.groupdict().items():
AttributeError: 'NoneType' object has no attribute 'groupdict'
```

**Comment by kinverarity1** [comment]
I won't fix these for now, where the header line is missing a period or colon. Instead, use ignore_header_errors.

```ipython
In [9]: las = lasio.read('../las/examples/kgs_downloads/2012/1044094833.las')
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
~\Code\lasio\lasio\reader.py in parse_header_section(sectdict, version, ignore_header_errors)
    446         try:
--> 447             values = read_line(line)
    448         except:

~\Code\lasio\lasio\reader.py in read_line(*args, **kwargs)
    609     '''
--> 610     return read_header_line(*args, **kwargs)
    611

~\Code\lasio\lasio\reader.py in read_header_line(line, pattern)
    635     m = re.match(pattern, line)
--> 636     mdict = m.groupdict()
    637     for key, value in mdict.items():

AttributeError: 'NoneType' object has no attribute 'groupdict'

During handling of the above exception, another exception occurred:

LASHeaderError                            Traceback (most recent call last)
<ipython-input-9-221a3cf5b910> in <module>()
----> 1 las = lasio.read('../las/examples/kgs_downloads/2012/1044094833.las')

~\Code\lasio\lasio\__init__.py in read(file_ref, **kwargs)
     41
     42     '''
---> 43     return LASFile(file_ref, **kwargs)

~\Code\lasio\lasio\las.py in __init__(self, file_ref, **read_kwargs)
     76
     77         if not (file_ref is None):
---> 78             self.read(file_ref, **read_kwargs)
     79
     80     def read(self, file_ref,

~\Code\lasio\lasio\las.py in read(self, file_ref, ignore_data, read_policy, null_policy, ignore_header_errors, **kwargs)
    165
    166         add_section("~W", "Well", version=version,
--> 167                     ignore_header_errors=ignore_header_errors)
    168
    169         # Establish NULL value if possible.

~\Code\lasio\lasio\las.py in add_section(pattern, name, **sect_kws)
    119             if raw_section:
    120                 self.sections[name] = reader.parse_header_section(raw_section,
--> 121                                                                   **sect_kws)
    122                 drop.append(raw_section["title"])
    123             else:

~\Code\lasio\lasio\reader.py in parse_header_section(sectdict, version, ignore_header_errors)
    453                 logger.warning(message)
    454             else:
--> 455                 raise exceptions.LASHeaderError(message)
    456         else:
    457             section.append(parser(**values))

LASHeaderError: line 14 (section ~Well Information Block): "COUNTY: RUSSELL"

In [10]: las = lasio.read('../las/examples/kgs_downloads/2012/1044094833.las', ignore_header_errors=True)
line 14 (section ~Well Information Block): "COUNTY: RUSSELL"

In [11]:
```
