### ISSUE TITLE
Parsing fails on parameter mnemonics containing whitespace after digits

### ISSUE THREAD

**Issue by da-wad** [kinverarity1/lasio#386]
I get the following traceback, which doesn't happen if I manually delete the offending parameter line:

```Parsing LAS files...
Unable to parse line as LAS header: BS1 .IN               22:   Bit size
Traceback (most recent call last):
  File "C:\<my-env>\lib\site-packages\lasio\reader.py", line 529, in parse_header_section
    values = read_line(line, section_name=parser.section_name2)
  File "C:\<my-env>\lib\site-packages\lasio\reader.py", line 714, in read_line
    return read_header_line(*args, **kwargs)
  File "C:\<my-env>\lib\site-packages\lasio\reader.py", line 780, in read_header_line
    mdict = m.groupdict()
AttributeError: 'NoneType' object has no attribute 'groupdict'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".\ingest\ingest.py", line 66, in <module>
    main()
  File ".\ingest\ingest.py", line 47, in main
    parsed_las_files = parse_las_files(las_files)
  File ".\ingest\ingest.py", line 28, in parse_las_files
    parsed_las_files = [(well_name, lasio.read(file)) for well_name, file in las_files.items()]
  File ".\ingest\ingest.py", line 28, in <listcomp>
    parsed_las_files = [(well_name, lasio.read(file)) for well_name, file in las_files.items()]
  File "C:\<my-env>\lib\site-packages\lasio\__init__.py", line 49, in read
    return LASFile(file_ref, **kwargs)
  File "C:\<my-env>\lib\site-packages\lasio\las.py", line 84, in __init__
    self.read(file_ref, **read_kwargs)
  File "C:\<my-env>\lib\site-packages\lasio\las.py", line 222, in read
    mnemonic_case=mnemonic_case,
  File "C:\<my-env>\lib\site-packages\lasio\las.py", line 142, in add_section
    raw_section, **sect_kws
  File "C:\<my-env>\lib\site-packages\lasio\reader.py", line 540, in parse_header_section
    raise exceptions.LASHeaderError(message)
lasio.exceptions.LASHeaderError: line 113 (section ~PARAMETER INFORMATION): "BS1 .IN               22:   Bit size"```

**Comment by kinverarity1** [comment]
@da-wad Thanks for the bug report! I think this was fixed in version 0.26 onwards (which was only released a little while ago). Please feel free to re-open the issue if you find it is not working for you on version 0.27:

[issue386.las.txt](https://github.com/kinverarity1/lasio/files/5212219/issue386.las.txt)

```python
>>> import lasio
>>> las = lasio.read('issue386.las')
>>> las.params
[HeaderItem(mnemonic="BS1", unit="IN", value="22", descr="Bit size")]
>>> print(lasio.__version__)
0.27
```

**Comment by da-wad** [comment]
The update fixed it - thanks 👍 
But my goodness you've been busy releasing... three since I went out on vacation!

**Comment by kinverarity1** [comment]
Not sure there are three releases worth of changes in there, but hey, it's just a number right? 😁

Thanks for the confirmation 👍
