### ISSUE TITLE
NULL. **** : NULL VALUE

### ISSUE THREAD

**Issue by VelizarVESSELINOV** [kinverarity1/lasio#82]
Funny NULL with not a numerical value, and really is present in the file:

```
NULL.                 **** : NULL VALUE
```

```
  10260.50         41.95
  10261.00          ****
  10261.50         40.29
```

**Comment by kinverarity1** [comment]
This is going to be difficult to handle without a refactor, because the data section is currently read in (and string substitutions necessarily applied) before the header sections are parsed. There probably isn't a reason we can't parse the header sections immediately on being read in, just needs work.

A test case which fails is attached.

```ipython
In [2]: las = lasio.read('../las/examples/null_star.las')
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
~\Code\lasio\lasio\reader.py in read_file_contents(file_obj, regexp_subs, value_null_subs, ignore_data)
    272                 try:
--> 273                     data = read_data_section_iterative(file_obj, regexp_subs, value_null_subs)
    274                 except:

~\Code\lasio\lasio\reader.py in read_data_section_iterative(file_obj, regexp_subs, value_null_subs)
    349
--> 350     array = np.fromiter(items(file_obj), np.float64, -1)
    351     for value in value_null_subs:

ValueError: could not convert string to float: '*****'

During handling of the above exception, another exception occurred:

LASDataError                              Traceback (most recent call last)
<ipython-input-2-d6759d77ee6a> in <module>()
----> 1 las = lasio.read('../las/examples/null_star.las')

~\Code\lasio\lasio\__init__.py in read(file_ref, **kwargs)
     41
     42     '''
---> 43     return LASFile(file_ref, **kwargs)

~\Code\lasio\lasio\las.py in __init__(self, file_ref, **read_kwargs)
     76
     77         if not (file_ref is None):
---> 78             self.read(file_ref, **read_kwargs)
     79
     80     def read(self, file_ref,

~\Code\lasio\lasio\las.py in read(self, file_ref, ignore_data, read_policy, null_policy, ignore_header_errors, **kwargs)
    106
    107         self.raw_sections = reader.read_file_contents(
--> 108             file_obj, regexp_subs, value_null_subs, ignore_data=ignore_data, )
    109
    110         if len(self.raw_sections) == 0:

~\Code\lasio\lasio\reader.py in read_file_contents(file_obj, regexp_subs, value_null_subs, ignore_data)
    275                     raise exceptions.LASDataError(
    276                         traceback.format_exc()[:-1] +
--> 277                         ' in data section beginning line {}'.format(i + 1))
    278                 sections[line] = {
    279                     "section_type": "data",

LASDataError: Traceback (most recent call last):
  File "C:\Users\kent\Code\lasio\lasio\reader.py", line 273, in read_file_contents
    data = read_data_section_iterative(file_obj, regexp_subs, value_null_subs)
  File "C:\Users\kent\Code\lasio\lasio\reader.py", line 350, in read_data_section_iterative
    array = np.fromiter(items(file_obj), np.float64, -1)
ValueError: could not convert string to float: '*****' in data section beginning line 20
```

[null_star.las.txt](https://github.com/kinverarity1/lasio/files/1464458/null_star.las.txt)
