### ISSUE TITLE
Non-Standard LAS - ASCII characters outside of allowed set in ~P section

### ISSUE THREAD

**Issue by tomtommahout** [kinverarity1/lasio#95]
Non-Standard LAS with ASCII characters outside of allowed set (° and ²). Setting `encoding='windows-1252'`, or `autodetect_encoding=True` doesn't seem to affect codec used.

(Very new to this, so apologies if its user error)

```
Connected to pydev debugger (build 135.1057)
C:\test\TESTBH_Moduli.las
Traceback (most recent call last):
  File "C:\Program Files (x86)\JetBrains\PyCharm Community Edition 3.4.1\helpers\pydev\pydevd.py", line 1733, in <module>
    debugger.run(setup['file'], None, None)
  File "C:\Program Files (x86)\JetBrains\PyCharm Community Edition 3.4.1\helpers\pydev\pydevd.py", line 1226, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\test_las_read.py", line 20, in <module>
    l = lasio.read(path, autodetect_encoding=True)
  File "C:\Python27\lib\site-packages\lasio\las.py", line 851, in read
    autodetect_encoding_chars=autodetect_encoding_chars)
  File "C:\Python27\lib\site-packages\lasio\las.py", line 166, in __init__
    autodetect_encoding_chars=autodetect_encoding_chars)
  File "C:\Python27\lib\site-packages\lasio\las.py", line 200, in read
    self._text = str(text)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xb0' in position 4319: ordinal not in range(128)
```

**Comment by kinverarity1** [comment]
Hello -- character encoding detection is not being automatically tested at the moment, so it's quite likely a bug with ``lasio`` -- all user reports of errors are very welcome!

A few suggestions/questions:

1. What version of ``lasio`` are you using? The reason I ask is that auto-detection of character encodings had a bug which was recently fixed. If you are not using the latest, try upgrading with ``pip install --upgrade lasio`` to see if that helps.

2. ``autodetect_encoding=True`` should work if you have either [cChardet](https://pypi.python.org/pypi/cchardet/) or [chardet](https://pypi.python.org/pypi/chardet/) installed, which it seems like you do as otherwise it would raise an ``ImportError`` instead of the error above.

3. Perhaps ``chardet`` is failing to detect the encoding correctly (although this seems unlikely) -- try also passing the keyword argument ``autodetect_encoding_chars=None``. This will allow ``chardet`` to scan the whole file.

4. If it's still not working, could you [upload](http://gist.github.com) or [send](mailto:kinverarity@hotmail.com) me the LAS file which isn't working (or a trimmed version if necessary)? I'll try to replicate the error.

**Comment by tomtommahout** [comment]
Hi Thanks for developing this - its a great library!  In response:
1. Version 0.7.7

2. cChardet installed - running this independently on the LAS file indicates encoding is u'Windows-1252' (That's why my query as to why the `UnicodeEncodeError` shows the ascii codec being used. But my knowledge is limited here.)

3. `autodetect_encoding_chars=None` gives the following - may be a separate bug?
```Traceback (most recent call last):
  File "C:\Program Files (x86)\JetBrains\PyCharm Community Edition 3.4.1\helpers\pydev\pydevd.py", line 1733, in <module>
    debugger.run(setup['file'], None, None)
  File "C:\Program Files (x86)\JetBrains\PyCharm Community Edition 3.4.1\helpers\pydev\pydevd.py", line 1226, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\test_las_read.py", line 27, in <module>
    l = lasio.read(path, autodetect_encoding=True, autodetect_encoding_chars=None)
  File "C:\Python27\lib\site-packages\lasio\las.py", line 851, in read
    autodetect_encoding_chars=autodetect_encoding_chars)
  File "C:\Python27\lib\site-packages\lasio\las.py", line 166, in __init__
    autodetect_encoding_chars=autodetect_encoding_chars)
  File "C:\Python27\lib\site-packages\lasio\las.py", line 185, in read
    autodetect_encoding_chars=autodetect_encoding_chars)
  File "C:\Python27\lib\site-packages\lasio\las.py", line 726, in open_file
    chunk = test_file.read(autodetect_encoding_chars)
TypeError: an integer is required```

4. File coming your way...!

**Comment by kinverarity1** [comment]
Thanks... yes seems like there might be a few problems hiding in there!
